config/routes.rb
FileBacon::Application.routes.draw do
  get "site/index"
  devise_for :users
  resources :docs

  root 'site#index'

end

app/models/doc.rb
class Doc < ActiveRecord::Base
    belongs_to :user

    # Model validations
    validates :user_id, presence: true
    validates :title, presence: true
    # ensure the url is present, and respects the URL format for http/https
    validates :url, format: {with: Regexp.new(URI::regexp(%w(http https)))}, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :docs

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_doc, only: [:show, :edit, :update, :destroy]
  
  # GET /docs
  # GET /docs.json
  def index
    @docs = current_user.docs.all
  end

  # GET /docs/1
  # GET /docs/1.json
  def show
  end

  # GET /docs/new
  def new
    @doc = current_user.docs.new
  end

  # GET /docs/1/edit
  def edit
  end

  # POST /docs
  # POST /docs.json
  def create
    @doc = current_user.docs.new(doc_params)

    respond_to do |format|
      if @doc.save
        format.html { redirect_to @doc, notice: 'Doc was successfully created.' }
        format.json { render action: 'show', status: :created, location: @doc }
      else
        format.html { render action: 'new' }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docs/1
  # PATCH/PUT /docs/1.json
  def update
    respond_to do |format|
      if @doc.update(doc_params)
        format.html { redirect_to @doc, notice: 'Doc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.json
  def destroy
    @doc.destroy
    respond_to do |format|
      format.html { redirect_to docs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doc
      unless @doc = current_user.docs.where(id: params[:id]).first
        flash[:alert] = 'Doc not found'
        redirect_to root_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doc_params
      params.require(:doc).permit(:title, :url, :file_type, :size)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    # Retrieve all documents ordered by descending creation timestamp
    @docs =  Doc.order('created_at desc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/docs/_form.html.erb
<%= simple_form_for(@doc) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :url %>
    <%= f.input :file_type %>
    <%= f.input :size %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/docs/edit.html.erb
<h1>Editing doc</h1>

<%= render 'form' %>

<%= link_to 'Show', @doc %> |
<%= link_to 'Back', docs_path %>

app/views/docs/index.html.erb
<h1>Listing docs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Type</th>
      <th>Size</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @docs.each do |doc| %>
      <tr>
        <td><%= doc.title %></td>
        <td><%= doc.url %></td>
        <td><%= doc.file_type %></td>
        <td><%= doc.size %></td>
        <td><%= link_to 'Show', doc %></td>
        <td><%= link_to 'Edit', edit_doc_path(doc) %></td>
        <td><%= link_to 'Destroy', doc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doc', new_doc_path %>

app/views/docs/new.html.erb
<h1>New doc</h1>

<%= render 'form' %>

<%= link_to 'Back', docs_path %>

app/views/docs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @doc.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @doc.url %>
</p>

<p>
  <strong>Type:</strong>
  <%= @doc.file_type %>
</p>

<p>
  <strong>Size:</strong>
  <%= @doc.size %>
</p>

<%= link_to 'Edit', edit_doc_path(@doc) %> |
<%= link_to 'Back', docs_path %>

app/views/layouts/_footer.html.erb
<hr>
<div>
    <p>This is a rails test app developed by <a href="http://akshaykatyal.info" target="_blank">Akshay Katyal</a>. Check the source code on <a href="http://github.com/MrDHat/FileBacon" target="_blank">GitHub</a>. </p>
</div>

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1>
        <%= link_to 'FileBacon', root_url %>
      </h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
        <% if user_signed_in? %>
          <li>
            <%= link_to 'Edit Profile', edit_user_registration_path %>
          </li>
          <li class="active">
            <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>        
          </li>
        <% else %>
          <li>
            <%= link_to 'Sign up', new_user_registration_path %>
          </li>
          <li class="active">
            <%= link_to 'Sign in', new_user_session_path %>  
          </li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body class="row">
    <div class="one columns centered">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= javascript_include_tag "application" %>
    </div>
  </body>
</html>

app/views/site/index.html.erb
<% if current_user %>
  <h2>Latest Documents</h2>
  <table style="width: 100%">
    <thead>
      <tr>
        <th>Url</th>
      </tr>
    </thead>

    <tbody>
    <% @docs.each do |doc| %>
      <tr>
        <td><%= link_to doc.title, doc.url %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
 
 <%= link_to 'New Doc', new_doc_path, :class => "button secondary" %>

<% else %>
  <div class="panel">
    <h1>Share your files!</h1>
    <p>A simple app to track and share your files with others.</p>
    <%= link_to "Get started today!", new_user_registration_path, :class => "button button-large" %>
  </div>
<% end %>